# Generated by Django 2.0.13 on 2019-04-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='uri',
        ),
    ]
