# Generated by Django 2.0.13 on 2019-04-06 06:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_images_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default=' ', null=True, upload_to='img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
